twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      navigation:
        topic   : navigation_cmd_vel
        timeout : 0.5
        priority: 10
      teleop:
        topic   : cmd_vel
        timeout : 0.5
        priority: 20
      joystick:
        topic   : safety_stop
        timeout : 0.5
        priority: 100